base_locale: en
locales:
  - en
  - th
data:
  read:
    - config/locales/%{locale}.yml
  write:
    - - config/locales/%{locale}.yml
search:
  paths:
    - app
    - config
ignore_unused:
  - auth.sessions.login_required
  - dental.*
