module Dental
  module ErrorCode
    NOT_FOUND = "NOT_FOUND".freeze
    VALIDATION_ERROR = "VALIDATION_ERROR".freeze
    INVALID_STAGE_TRANSITION = "INVALID_STAGE_TRANSITION".freeze
    STATE_GUARD_VIOLATION = "STATE_GUARD_VIOLATION".freeze
    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK".freeze
    DUPLICATE_ENTRY = "DUPLICATE_ENTRY".freeze
    STALE_UPDATE_CONFLICT = "STALE_UPDATE_CONFLICT".freeze
    UNAUTHORIZED = "UNAUTHORIZED".freeze
    FORBIDDEN = "FORBIDDEN".freeze
    CONTRACT_MISMATCH = "CONTRACT_MISMATCH".freeze
    EXTERNAL_INTEGRATION_UNAVAILABLE = "EXTERNAL_INTEGRATION_UNAVAILABLE".freeze

    ALL = [
      NOT_FOUND,
      VALIDATION_ERROR,
      INVALID_STAGE_TRANSITION,
      STATE_GUARD_VIOLATION,
      INSUFFICIENT_STOCK,
      DUPLICATE_ENTRY,
      STALE_UPDATE_CONFLICT,
      UNAUTHORIZED,
      FORBIDDEN,
      CONTRACT_MISMATCH,
      EXTERNAL_INTEGRATION_UNAVAILABLE
    ].freeze
  end
end
